# ============================================
# BoT-SORT
# Handheld smartphone traffic video
# ============================================

tracker_type: botsort

# First association
track_high_thresh: 0.20

# Low-confidence association
track_low_thresh: 0.10

# New track initialization
new_track_thresh: 0.20

# Keep temporarily lost objects alive
track_buffer: 90

# Association threshold
match_thresh: 0.80

# Fuse detection confidence with IoU distance
fuse_score: True

# Handheld camera stabilization
gmc_method: sparseOptFlow

# Disable ReID for first experiment
with_reid: True

# Required by current Ultralytics BoT-SORT API
model: auto

# ReID parameters
proximity_thresh: 0.50
appearance_thresh: 0.80
